export const challengesData = [
  { "id": 1, "title": "Matikan lampu siang hari", "category": "aksi lingkungan" },
  { "id": 2, "title": "Cabut charger selesai pakai", "category": "aksi lingkungan" },
  { "id": 3, "title": "Buka jendela tiap pagi", "category": "kesehatan" },
  { "id": 4, "title": "Gunakan kipas, bukan AC", "category": "aksi lingkungan" },
  { "id": 5, "title": "Gunakan lampu LED", "category": "aksi lingkungan" },
  { "id": 6, "title": "Matikan TV tak ditonton", "category": "aksi lingkungan" },
  { "id": 7, "title": "Tutup kran saat sikat gigi", "category": "aksi lingkungan" },
  { "id": 8, "title": "Gunakan air secukupnya", "category": "aksi lingkungan" },
  { "id": 9, "title": "Pakai gayung saat mandi", "category": "aksi lingkungan" },
  { "id": 10, "title": "Gunakan ember, bukan selang", "category": "aksi lingkungan" },
  { "id": 11, "title": "Masak air secukupnya", "category": "aksi lingkungan" },
  { "id": 12, "title": "Gunakan panci bertutup", "category": "aksi lingkungan" },
  { "id": 13, "title": "Gunakan lap kain", "category": "aksi lingkungan" },
  { "id": 14, "title": "Gunakan wadah bekas", "category": "aksi lingkungan" },
  { "id": 15, "title": "Cuci baju sekali banyak", "category": "aksi lingkungan" },
  { "id": 16, "title": "Gunakan sabun isi ulang", "category": "aksi lingkungan" },
  { "id": 17, "title": "Gunakan air bilasan ulang", "category": "aksi lingkungan" },
  { "id": 18, "title": "Jemur pakaian di matahari", "category": "aksi lingkungan" },
  { "id": 19, "title": "Kurangi pemakaian tisu", "category": "aksi lingkungan" },
  { "id": 20, "title": "Hemat listrik harian", "category": "aksi lingkungan" },

  { "id": 21, "title": "Bawa tas belanja sendiri", "category": "aksi lingkungan" },
  { "id": 22, "title": "Tolak kantong plastik", "category": "aksi lingkungan" },
  { "id": 23, "title": "Beli sayur di pasar", "category": "aksi lingkungan" },
  { "id": 24, "title": "Pilih produk lokal", "category": "aksi lingkungan" },
  { "id": 25, "title": "Bawa wadah sendiri", "category": "aksi lingkungan" },
  { "id": 26, "title": "Pilih sabun batang", "category": "aksi lingkungan" },
  { "id": 27, "title": "Hindari kemasan berlebihan", "category": "aksi lingkungan" },
  { "id": 28, "title": "Beli seperlunya saja", "category": "aksi lingkungan" },
  { "id": 29, "title": "Gunakan tumbler minum", "category": "aksi lingkungan" },
  { "id": 30, "title": "Bawa sendok sendiri", "category": "aksi lingkungan" },
  { "id": 31, "title": "Pilih isi ulang produk", "category": "aksi lingkungan" },
  { "id": 32, "title": "Gunakan keranjang belanja", "category": "aksi lingkungan" },
  { "id": 33, "title": "Hindari minuman botolan", "category": "aksi lingkungan" },
  { "id": 34, "title": "Pilih barang tahan lama", "category": "aksi lingkungan" },
  { "id": 35, "title": "Kurangi belanja online", "category": "aksi lingkungan" },
  { "id": 36, "title": "Bawa kotak makan sendiri", "category": "aksi lingkungan" },
  { "id": 37, "title": "Beli sayur musiman", "category": "aksi lingkungan" },
  { "id": 38, "title": "Gunakan uang digital", "category": "aksi lingkungan" },
  { "id": 39, "title": "Hindari belanja impulsif", "category": "pembelajaran" },
  { "id": 40, "title": "Pilih bahan alami", "category": "aksi lingkungan" },

  { "id": 41, "title": "Masak secukupnya", "category": "aksi lingkungan" },
  { "id": 42, "title": "Simpan sisa nasi", "category": "aksi lingkungan" },
  { "id": 43, "title": "Gunakan minyak dua kali", "category": "aksi lingkungan" },
  { "id": 44, "title": "Buat ecoenzyme sederhana", "category": "pembelajaran" },
  { "id": 45, "title": "Cuci sayur di baskom", "category": "aksi lingkungan" },
  { "id": 46, "title": "Gunakan air cucian beras", "category": "aksi lingkungan" },
  { "id": 47, "title": "Simpan makanan tertutup", "category": "kesehatan" },
  { "id": 48, "title": "Kurangi masak instan", "category": "kesehatan" },
  { "id": 49, "title": "Gunakan wadah kaca", "category": "aksi lingkungan" },
  { "id": 50, "title": "Gunakan sendok logam", "category": "aksi lingkungan" },
  { "id": 51, "title": "Gunakan kompor api kecil", "category": "aksi lingkungan" },
  { "id": 52, "title": "Kurangi plastik dapur", "category": "aksi lingkungan" },
  { "id": 53, "title": "Gunakan daun pisang", "category": "aksi lingkungan" },
  { "id": 54, "title": "Buat pupuk dapur sendiri", "category": "pembelajaran" },
  { "id": 55, "title": "Simpan makanan di kulkas", "category": "kesehatan" },
  { "id": 56, "title": "Buat bumbu sekaligus", "category": "aksi lingkungan" },
  { "id": 57, "title": "Gunakan piring yang sama", "category": "aksi lingkungan" },
  { "id": 58, "title": "Gunakan taplak kain", "category": "aksi lingkungan" },
  { "id": 59, "title": "Kurangi pemborosan gas", "category": "aksi lingkungan" },
  { "id": 60, "title": "Gunakan kain lap alami", "category": "aksi lingkungan" },

  { "id": 61, "title": "Tanam cabai di pot", "category": "aksi lingkungan" },
  { "id": 62, "title": "Tanam daun bawang", "category": "aksi lingkungan" },
  { "id": 63, "title": "Siram tanaman tiap pagi", "category": "aksi lingkungan" },
  { "id": 64, "title": "Gunakan air bekas siram", "category": "aksi lingkungan" },
  { "id": 65, "title": "Kumpulkan daun jadi kompos", "category": "pembelajaran" },
  { "id": 66, "title": "Gunakan pot bekas ember", "category": "aksi lingkungan" },
  { "id": 67, "title": "Tanam bunga halaman", "category": "aksi lingkungan" },
  { "id": 68, "title": "Rawat tanaman hias kecil", "category": "aksi lingkungan" },
  { "id": 69, "title": "Gunakan pupuk organik", "category": "aksi lingkungan" },
  { "id": 70, "title": "Tanam lidah buaya", "category": "aksi lingkungan" },
  { "id": 71, "title": "Buat biopori sederhana", "category": "pembelajaran" },
  { "id": 72, "title": "Gunakan air hujan", "category": "aksi lingkungan" },
  { "id": 73, "title": "Ajak anak menanam", "category": "pembelajaran" },
  { "id": 74, "title": "Tanam serai di pot", "category": "aksi lingkungan" },
  { "id": 75, "title": "Tanam tanaman obat", "category": "aksi lingkungan" },
  { "id": 76, "title": "Siram tanaman sore hari", "category": "aksi lingkungan" },
  { "id": 77, "title": "Buat rak tanaman bekas", "category": "aksi lingkungan" },
  { "id": 78, "title": "Tanam tanaman anti nyamuk", "category": "aksi lingkungan" },
  { "id": 79, "title": "Gunakan pot daur ulang", "category": "aksi lingkungan" },
  { "id": 80, "title": "Beri nama tanamanmu", "category": "pembelajaran" },

  { "id": 81, "title": "Buang sampah pada tempatnya", "category": "aksi lingkungan" },
  { "id": 82, "title": "Pisahkan sampah rumah", "category": "aksi lingkungan" },
  { "id": 83, "title": "Daur ulang botol bekas", "category": "pembelajaran" },
  { "id": 84, "title": "Gunakan kardus bekas", "category": "aksi lingkungan" },
  { "id": 85, "title": "Donasikan baju lama", "category": "aksi lingkungan" },
  { "id": 86, "title": "Ajak anak memilah sampah", "category": "pembelajaran" },
  { "id": 87, "title": "Gunakan kalender bekas", "category": "aksi lingkungan" },
  { "id": 88, "title": "Kurangi waktu layar", "category": "kesehatan" },
  { "id": 89, "title": "Hemat listrik keluarga", "category": "aksi lingkungan" },
  { "id": 90, "title": "Ajak keluarga hemat air", "category": "pembelajaran" },
  { "id": 91, "title": "Hari bebas plastik mingguan", "category": "aksi lingkungan" },
  { "id": 92, "title": "Gunakan masker kain", "category": "aksi lingkungan" },
  { "id": 93, "title": "Gunakan kipas tangan", "category": "aksi lingkungan" },
  { "id": 94, "title": "Kurangi AC di rumah", "category": "aksi lingkungan" },
  { "id": 95, "title": "Gunakan waktu jemur alami", "category": "aksi lingkungan" },
  { "id": 96, "title": "Tanam pohon tiap tahun", "category": "aksi lingkungan" },
  { "id": 97, "title": "Gunakan sabun ramah lingkungan", "category": "aksi lingkungan" },
  { "id": 98, "title": "Edukasi anak tentang bumi", "category": "pembelajaran" },
  { "id": 99, "title": "Bersihkan rumah tanpa kimia", "category": "kesehatan" },
  { "id": 100, "title": "Syukuri bumi setiap hari", "category": "pembelajaran" }
]
